name: Test
on:
  workflow_dispatch:

jobs:
  calculate-and-send:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      #  with:
      #    repository: ${{ vars.REPOSITORY }}
      #    ref: ${{ vars.REF }}

      - name: Setup uv
        uses: astral-sh/setup-uv@v7.1.4


      - name: Run script
        env:
          ZOTERO_ID: ${{ secrets.ZOTERO_ID }}
          ZOTERO_KEY: ${{ secrets.ZOTERO_KEY }}
          SENDER: ${{ secrets.SENDER }}
          RECEIVER: ${{ secrets.RECEIVER }}
          SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
          EMAIL_ENABLED: ${{ vars.EMAIL_ENABLED }}
          WECHAT_PUSH_PROVIDER: ${{ vars.WECHAT_PUSH_PROVIDER }}
          SERVERCHAN_SENDKEY: ${{ secrets.SERVERCHAN_SENDKEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_API_BASE: ${{ vars.OPENAI_API_BASE }}
          OPENAI_API_TIMEOUT: ${{ vars.OPENAI_API_TIMEOUT }}
          DASHSCOPE_API_KEY: ${{ secrets.DASHSCOPE_API_KEY }}
          DASHSCOPE_API_BASE: ${{ vars.DASHSCOPE_API_BASE }}
          DASHSCOPE_API_TIMEOUT: ${{ vars.DASHSCOPE_API_TIMEOUT }}
          EMBEDDING_MODEL: ${{ vars.EMBEDDING_MODEL }}
          ARXIV_EXTRACT_FULL_TEXT: ${{ vars.ARXIV_EXTRACT_FULL_TEXT }}
          CUSTOM_CONFIG: ${{ vars.CUSTOM_CONFIG }}
        run: |
          export DEBUG=true
          export DEBUG_PAPER_LIMIT=1
          if [ -n "$CUSTOM_CONFIG" ]; then
            printf "%b\n" "$CUSTOM_CONFIG" > config/custom.yaml
          fi
          echo "Use custom config: "
          cat config/custom.yaml
          uv run src/zotero_arxiv_daily/main.py executor.source='[arxiv]' executor.max_paper_num=1
